config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes

  root to: "notes#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	validates :name, :content, :user_id, :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user! #if user is not logged in redirect to log in page
  before_action :set_note, only: [:show, :edit, :update, :destroy] 
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :category, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Michno</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('MichnoNotepad', notes_path, :class => "active", :class => "navbar-brand") %>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to('Notes', notes_path, :class => "active") %>  </li>
       	<li><%= link_to 'New Note', new_note_path %></li>

      </ul> 
	<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	<li class="navbar-text">Current user: <%= current_user.email %></li>
	<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  </li>
	<% end %>
	</ul>    
    </div>
  </div>
</nav>




<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,  :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>
<div class="btn-group">
  <%= link_to 'Show', @note, :class => "btn btn-default" %>
  <%= link_to 'Back', notes_path, :class => "btn btn-default" %>
</div>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

  <% @notes.each do |note| %>
    <div class="panel panel-default">
      <div class="panel-heading"><b><%= note.name %></b>(<%= note.category %>) by <%= note.user.email %></div>
        <div class="panel-body">
          <p>
            <%= note.content %>
          </p>
    
          <div class="btn-group">
            <%= link_to 'Show', note, :method => :get, :class => "btn btn-default" %>
            <%= link_to 'Edit', edit_note_path(note), :method => :get, :class => "btn btn-default" %>
            <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default"%>
          </div>  
        </div>
    </div>

  <% end %>


<br>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path, :class => "btn btn-default" %>

app/views/notes/show.html.erb
<% if !notice.blank? %>
<div class="alert alert-info"><%= notice %></div>
<% end %>
   <div class="panel panel-default">
      <div class="panel-heading"><b><%= @note.name %></b>(<%= @note.category %>) by <%= @note.user.email %></div>
        <div class="panel-body">
          <p>
            <%= @note.content %>
          </p>
    <div class="btn-group">
  <%= link_to 'Destroy', @note, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default"%>
  <%= link_to 'Edit', edit_note_path(@note), :class => "btn btn-default" %>
  <%= link_to 'Back', notes_path , :class => "btn btn-default" %>
</div>

   
    </div>